services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - db
      - rabbitmq
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: billing_db
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data: {}

networks:
  app_network:
    driver: bridge
