# Generated by Django 5.1.1 on 2024-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("sent", "Sent"), ("paid", "Paid")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
